// <auto-generated />
namespace ODL.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Avtal_Ansvarig_NotNull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Avtal_Ansvarig_NotNull));
        
        string IMigrationMetadata.Id
        {
            get { return "201705091026267_Avtal_Ansvarig_NotNull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
