// <auto-generated />
namespace ODL.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Namnbyte_HuvudsakligtKostnadsstalle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Namnbyte_HuvudsakligtKostnadsstalle));
        
        string IMigrationMetadata.Id
        {
            get { return "201705180545070_Namnbyte_HuvudsakligtKostnadsstalle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
