// <auto-generated />
namespace ODL.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GatuAdress_till_Gatuadress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GatuAdress_till_Gatuadress));
        
        string IMigrationMetadata.Id
        {
            get { return "201705091043185_GatuAdress_till_Gatuadress"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
